# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.7.4
matrix:
  include:
    - python: 3.7.4
      dist: xenial

# Install the requirements and codecov pip dependency
install:
  - pip install -r requirements.txt
  - pip install codecov

# Run the unit test
script:
  - python test_image.py
  - coverage run test_image.py

# Push the results back to codecov
after_success:
  - codecov