# Disable sudo to speed up the build
#sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.7.4
matrix:
  include:
    - python: 3.7.4
      dist: xenial
      #sudo: true

# Install the codecov pip dependency
install:
  - pip install -r requirements.txt

# Run the unit test
script:
#  - coverage run tests.py
  - test_image.py